# Generated by Django 2.0 on 2018-09-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='g',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='key',
            name='p',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='key',
            name='x',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='y',
            field=models.BigIntegerField(),
        ),
    ]
