# Generated by Django 2.0 on 2018-09-21 15:22

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_vote_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='a',
            field=base.models.BigBigField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='b',
            field=base.models.BigBigField(),
        ),
    ]
